name: CI

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true

      - name: Create Package
        uses: BigWigsMods/packager@master
        with:
          args: -dz
        # env:
        #   CF_API_KEY: ${{ secrets.CF_API_KEY }}
        #   GITHUB_OAUTH: ${{ secrets.GITHUB_OAUTH }}

      - name: Fix Namespaces
        uses: emptyrivers/wow-xml-namespacer@main
        with:
          name: Bisector
          path: .release/Bisector/ClipBoard

      - name: Upload Package
        uses: BigWigsMods/packager@master
        with:
          args: -eld

      - uses: actions/upload-artifact@v1.0.0
        with:
          name: Bisector-CI
          path: .release/Bisector
